### ISSUE TITLE
Unable to make changes in settings menu

### ISSUE THREAD

**Issue by rcarteraz** [sudobox-io/sb-cli#1]
When you select an option to make a change in the settings menu, it does not prompt to actually change it. The menu flashes and you are left having to select again. Same issue for each option.

**Comment by Xarritomi** [comment]
This is actually an intended output. In future, the coming updates will enable this feature. It is our fault though for not specifying this.

**Comment by rcarteraz** [comment]
> 

Ah okay. Yeah, definitely would recommend adding the (coming soon) to that one too.
